# Generated by Django 3.0 on 2019-12-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('father_name', models.CharField(max_length=52)),
                ('roll', models.CharField(max_length=52)),
                ('s_name', models.CharField(max_length=52)),
                ('address', models.CharField(max_length=52)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
